# Generated by Django 4.1.2 on 2022-10-26 12:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Faqat O`zbekiston mobil raqamlari tasdiqlanadi('+' belgisiz!)", regex='^998[0-9]{2}[0-9]{7}$')], verbose_name='Telefon raqam')),
                ('first_name', models.CharField(max_length=50, verbose_name='Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Surname')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(blank=True, choices=[('director', 'director'), ('seller', 'seller'), ('client', 'client')], max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
